version: '3'

services:

  store:
    image:  progrium/consul:latest
    command: "-server -bootstrap -ui-dir /ui -recursor=192.168.2.1"
    container_name: consul
    ports:
      - "8500:8500"
      - "8400:8400"
      - "53:53/udp"
     

  registrator:
    image: gliderlabs/registrator:latest
    command: "-ip localhost consul://localhost:8500"
    container_name: registrator
    network_mode: "host"
    depends_on:
      - store
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock

