version: '3'

services:
  kong-db:
    image: cassandra:3
    dns: 172.17.0.1
    dns_search: service.consul
    network_mode: "bridge"
    ports:
      - "9042:9042"
    environment:
      SERVICE_9042_NAME: kongdb

  kong:
    image: kong:latest
    dns: 172.17.0.1
    dns_search: service.consul
    network_mode: "bridge"
    depends_on:
      - kong-db
    links:
      - kong-db
    retart: always
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "7946:7946"
      - "7946:7946/udp"
    environment:
      KONG_DATABASE: cassandra
      KONG_CASSANDRA_CONTACT_POINTS: kong-database
      KONG_PG_HOST: kong-database
      SERVICE_8000_NAME: apigateway
      SERVICE_8001_NAME: apigateway-admin
