version: "3"

services:

  kafka:
    image: spotify/kafka:latest
    container_name: kafka
    ports:
      - "2181:2181"
      - "9092:9092"
    dns: localhost
    dns_search: service.consul
    environment:
      - ADVERTISED_HOST=localhost
      - ADVERTISED_PORT=9092
      - SERVICE_9092_NAME=eventstore
      
