version: "3"

services:

  kafka:
    image: spotify/kafka:latest
    container_name: kafka 
    ports:
      - "2181:2181"
      - "9092:9092"
    dns: 172.17.0.1
    dns_search: service.consul
    networks:
      - registry_registry_network
    environment:
      - ADVERTISED_HOST=localhost
      - ADVERTISED_PORT=9092
      - SERVICE_9092_NAME=eventstore

networks:
  registry_registry_network:
    external: true      
